package main

//go:generate go-bindata -nomemcopy -pkg main -prefix templates/ -ignore .git/ -ignore README.md -ignore generate.go -ignore bindata.go -ignore .gitignore -ignore .idea -o bindata.go ./...
